steps:

- id: "Go mod init"
  name: 'golang'
  args: ['go', 'mod', 'init', 'github.com/leticiapillar/gcp-go-sum']

- id: "Go test"
  name: 'golang'
  args: ['go', 'test', '-v', 'src/soma/main_test.go', 'src/soma/main.go']

- id: "Docker build"
  name: 'docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gcp-go-sum', '.']

